### ISSUE TITLE
CONSOLE ERROR

### ISSUE THREAD

**Issue by Kanekii04** [PluginBugs/Issues-ServerBooster#35]
**Describe the bug**
Hello. Iam getting this problem in the console, its spamming all the time
[13:59:46] [Server thread/WARN]: [ServerBooster] Task #12 for ServerBooster v1.0.49 generated an exception
java.lang.NoSuchFieldError: trackedEntities
        at dev.lone.serverbooster.c.h.b.a.a(SourceFile:339) ~[?:?]
        at dev.lone.serverbooster.c.h.b.c.b(SourceFile:44) ~[?:?]
        at dev.lone.serverbooster.c.h.b.c.run(SourceFile:26) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**To Reproduce**

**Expected behavior**
.

**Screenshots**
.

**Info (please complete the following information):**
 - Server version: Spigot 1.16.4
 - Client version: Vanila
 - Plugin version: 1.0.49

**Additional context**
nothing

**Comment by LoneDev6** [comment]
Hello,
Download latest paper or spigot and use it.
You can get it easily from here:
https://serverjars.com/

This error is generated by a broken jar file as the `trackedEntities` do exists in Minecraft.

Let me know :D

**Comment by Kanekii04** [comment]
Hello. I writed u on discord, well its not working. :/

**Comment by LoneDev6** [comment]
open a ticket and send us the jar file of your server, thanks.

https://support.plugin.ga

**Comment by jwpjrdev** [comment]
Please do not encourage the use of pre-compiled Spigot jars. It is illegal to distribute the code in binary form.

Instead, use BuildTools: https://www.spigotmc.org/wiki/buildtools/

**Comment by LoneDev6** [comment]
> 
> 
> Please do not encourage the use of pre-compiled Spigot jars. It is illegal to distribute the code in binary form.
> 
> Instead, use BuildTools: https://www.spigotmc.org/wiki/buildtools/

Users don't understand how to use build tools. ServerJars is useful as they build spigot each day to have the most recent one.

You should report that to the ServerJars owners, not here.
Thanks

**Comment by jwpjrdev** [comment]
There are instructions on the page. It's simple if you're willing to put in the effort. It's that or break the law.

Besides, afaik, Songoda doesn't care.
