### ISSUE TITLE
[BUG] 1.1.1 version, Drops not counting

### ISSUE THREAD

**Issue by WongIong** [PluginBugs/Issues-ServerBooster#56]
**Describe the bug**
Enabled the drops grupping feature
Drop more than 2 items on the ground
You can only pick up 1 item

**To Reproduce**
See above

**Expected behavior**
Count the drop again

**Screenshots**

**Info (please complete the following information):**
 - Server version: 1.17.1 paper 411
 - Client version: 1.17.1
 - Plugin version: 1.1.1

**Additional context**

**Comment by WongIong** [comment]
[07:12:40] [Server thread/INFO]: [ServerBooster] Loading ServerBooster v1.1.1
[07:13:04] [Server thread/INFO]: [ServerBooster] Enabling ServerBooster v1.1.1
[07:13:04] [Server thread/WARN]: [ServerBooster] Invalid configuration for mob type: pig_zombie
[07:13:05] [Server thread/WARN]: [ServerBooster] Loaded class com.comphenix.protocol.reflect.FieldUtils from ProtocolLib v4.8.0 which is not a depend, softdepend or loadbefore of this plugin.
[07:20:19] [Server thread/INFO]: [ServerBooster] Disabling ServerBooster v1.1.1

**Comment by tom4712** [comment]
Could not pass event PlayerDropItemEvent to ServerBooster v1.1.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]

**Comment by Nemozxy** [comment]
me too

**Comment by LoneDev6** [comment]
I need full server logs, not only parts of errors
