### ISSUE TITLE
1.19.2 been Removed?

### ISSUE THREAD

**Issue by Teddy20002** [PluginBugs/Issues-ServerBooster#71]
Server Booster 1.1.3-r4 Doesn't support 1.19.2 did you removed it from this version?

**Expected behavior**
[14:00:18] [Server thread/WARN]: [ServerBooster] Invalid configuration for mob type: pig_zombie
[14:00:18] [Server thread/ERROR]: [ServerBooster] Error getting implementation for class dev.lone.serverbooster.entities_tracking.nms.Nms - NMS v1_19_R1
[14:00:18] [Server thread/WARN]: java.lang.ClassNotFoundException: dev.lone.serverbooster.entities_tracking.nms.impl.v1_19_R1.NMSHandler
[14:00:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177)
[14:00:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[14:00:18] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[14:00:18] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[14:00:18] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[14:00:18] [Server thread/WARN]: 	at ServerBooster_1.1.3-r4.jar//dev.lone.serverbooster.entities_tracking.nms.Nms.a(SourceFile:40)
[14:00:18] [Server thread/WARN]: 	at ServerBooster_1.1.3-r4.jar//dev.lone.serverbooster.entities_tracking.nms.Nms.a(SourceFile:15)
[14:00:18] [Server thread/WARN]: 	at ServerBooster_1.1.3-r4.jar//dev.lone.serverbooster.main.au.o(SourceFile:108)
[14:00:18] [Server thread/WARN]: 	at ServerBooster_1.1.3-r4.jar//dev.lone.serverbooster.main.au.r(SourceFile:214)
[14:00:18] [Server thread/WARN]: 	at ServerBooster_1.1.3-r4.jar//dev.lone.serverbooster.Main.onEnable(SourceFile:130)
[14:00:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:00:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:00:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[14:00:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[14:00:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[14:00:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[14:00:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[14:00:18] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[14:00:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[14:00:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[14:00:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:00:18] [Server thread/INFO]: [ServerBooster] Disabling ServerBooster v1.1.3-r4
[14:00:18] [Server thread/ERROR]: [ServerBooster] Could not find support for this Spigot version.
[14:00:18] [Server thread/ERROR]: Error occurred while enabling ServerBooster v1.1.3-r4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.lone.serverbooster.entities_tracking.nms.INms.t()" because "dev.lone.serverbooster.main.au.a" is null
	at dev.lone.serverbooster.main.au.o(SourceFile:111) ~[ServerBooster_1.1.3-r4.jar:?]
	at dev.lone.serverbooster.main.au.r(SourceFile:214) ~[ServerBooster_1.1.3-r4.jar:?]
	at dev.lone.serverbooster.Main.onEnable(SourceFile:130) ~[ServerBooster_1.1.3-r4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]

**Screenshots**

**Info (please complete the following information):**
 - Server version: (example: paper 1.15.2) 1.19.2
 - Client version: (example: fabric 1.15.2) 1.19.2
 - Plugin version: (example: 2.0.9 do not write "latest") 1.1.3-r4

**Additional context**

**Comment by LoneDev6** [comment]
Yes as they are old and bugged.
Upgrade to 1.19.3 or 1.19.4.
